/*
 * generated by Xtext 2.25.0
 */
package org.example.domainmodel.ide;


/**
 * Use this class to register ide components.
 */
public class DomainmodelIdeModule extends AbstractDomainmodelIdeModule {
}
